### ISSUE TITLE
Implement beatmap submission logic

### ISSUE THREAD

**Issue by Lekuruu** [hexis-revival/hexagon#21]
- [x] Database schema ( https://github.com/hexis-revival/hexagon-deploy/pull/1 )
- [x] Endpoint reverse-engineering & basic implementation ( https://github.com/hexis-revival/hexagon/compare/8465a04f4f8014e014932cbf800214f50a6d52d4...0048825794915a1b335ba180a6ae74f455000cb3 )
- [x] Endpoints
  - [x] `/web/bss-genid.php` ( #27 )
  - [x] `/web/bss-upload.php` ( #29 )
  - [x] `/web/bss-gentid.php` ( #30 )
  - [x] `/web/bss-post.php` ( #31 )
- [ ] Forum database schema
  - [x] Schema definition (https://github.com/hexis-revival/hexagon-deploy/pull/2)
  - [ ] Implementation in hexagon ( #35 )
